<?php

// This file was generated by running "composer dump-env local"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '16b53ce8e380a51434f97b676c44b85b',
  'DATABASE_URL' => 'mysql://root:root@localhost:3307/detoqueytoque_rifas_local_test?serverVersion=mariadb-10.4.11',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1|devadmin\\.detoqueytoque\\.com|inscripcion\\.detoqueytoque\\.com|devrifas\\.detoqueytoque\\.com)(:[0-9]+)?$',
  'MAILER_DSN' => 'gmail://seijitsumura1985@gmail.com:pbujncikxcyykyev@default?verify_peer=0',
  'URL_ENV_API' => 'https://api-rifas.ct.ws/',
  'URL_RAIZ_SERVER' => 'https://toqueytoque.ct.ws',
  'URL_LINK_PAGO' => 'https://user-rifas.ct.ws',
  'URL_ENV_FRONT_RIFA' => 'https://user-rifas.ct.ws',
  'URL_ENV_FRONT_ADMIN' => 'https://admin-rifas.ct.ws',
);