<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226094141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aereopuerto (id INT AUTO_INCREMENT NOT NULL, ciudad_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, codigo VARCHAR(255) NOT NULL, INDEX IDX_17057EAE8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alojamiento (id INT AUTO_INCREMENT NOT NULL, alojamiento_tipo_id INT NOT NULL, proveedor_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, image_src VARCHAR(255) DEFAULT NULL, INDEX IDX_26918125DA231D27 (alojamiento_tipo_id), INDEX IDX_26918125CB305D73 (proveedor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alojamiento_tipo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE archivo (id INT AUTO_INCREMENT NOT NULL, documento_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, fecha_creado DATE NOT NULL, INDEX IDX_3529B48245C0CF75 (documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE campos_tipotransporte (id INT AUTO_INCREMENT NOT NULL, transporte_tipo_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, obligatorio TINYINT(1) DEFAULT NULL, aeropuerto TINYINT(1) DEFAULT NULL, INDEX IDX_526485EEAC5ED017 (transporte_tipo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ciudad (id INT AUTO_INCREMENT NOT NULL, pais_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, nombre_ingles VARCHAR(255) DEFAULT NULL, descripcion LONGTEXT DEFAULT NULL, latitud VARCHAR(255) DEFAULT NULL, longitud VARCHAR(255) DEFAULT NULL, image_src VARCHAR(255) DEFAULT NULL, INDEX IDX_8E86059EC604D5C6 (pais_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ciudad_campos (id INT AUTO_INCREMENT NOT NULL, ciudad_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, valor LONGTEXT DEFAULT NULL, INDEX IDX_80D6DA1E8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comprador (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, celular VARCHAR(255) DEFAULT NULL, departamento VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE costo_extra (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, descripcion VARCHAR(255) NOT NULL, monto DOUBLE PRECISION NOT NULL, fecha DATETIME NOT NULL, INDEX IDX_68520204704716FE (pasajero_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE datos_tipo_transporte (id INT AUTO_INCREMENT NOT NULL, campos_tipo_transporte_id INT NOT NULL, transporte_id INT NOT NULL, aereopuerto_id INT DEFAULT NULL, valor LONGTEXT NOT NULL, INDEX IDX_FE07457CE847570D (campos_tipo_transporte_id), INDEX IDX_FE07457C24FC919A (transporte_id), INDEX IDX_FE07457C67CB2AE8 (aereopuerto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE deposito (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, monto DOUBLE PRECISION NOT NULL, tipo VARCHAR(255) NOT NULL, fecha DATETIME NOT NULL, fecha_procesado DATETIME DEFAULT NULL, csv TINYINT(1) NOT NULL, comentario LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', geopay TINYINT(1) DEFAULT NULL, INDEX IDX_509FC0D1704716FE (pasajero_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documento (id INT AUTO_INCREMENT NOT NULL, tipo_documento_id INT DEFAULT NULL, pais_id INT DEFAULT NULL, persona_id INT DEFAULT NULL, numero VARCHAR(50) DEFAULT NULL, serie VARCHAR(50) DEFAULT NULL, fecha_expedicion DATE DEFAULT NULL, fecha_vencimiento DATE DEFAULT NULL, imagen_url VARCHAR(100) DEFAULT NULL, INDEX IDX_B6B12EC7F6939175 (tipo_documento_id), INDEX IDX_B6B12EC7C604D5C6 (pais_id), INDEX IDX_B6B12EC7F5F88DB9 (persona_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etiqueta (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etiqueta_pasajero (id INT AUTO_INCREMENT NOT NULL, etiqueta_id INT DEFAULT NULL, pasajero_id INT DEFAULT NULL, comentario VARCHAR(255) DEFAULT NULL, INDEX IDX_BE362F4BD53DA3AB (etiqueta_id), INDEX IDX_BE362F4B704716FE (pasajero_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forgot_password (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, token VARCHAR(300) NOT NULL, expire DATETIME NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_2AB9B566A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE foto_persona (id INT AUTO_INCREMENT NOT NULL, persona_id INT DEFAULT NULL, fecha DATE DEFAULT NULL, url VARCHAR(255) NOT NULL, nombre VARCHAR(100) NOT NULL, tipo VARCHAR(50) DEFAULT NULL, INDEX IDX_43618E61F5F88DB9 (persona_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grupo (id INT AUTO_INCREMENT NOT NULL, viaje_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8C0E9BD394E1E648 (viaje_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE historial_transferencias (id INT AUTO_INCREMENT NOT NULL, talon_id INT NOT NULL, pasajero_id INT NOT NULL, fecha DATETIME NOT NULL, accion VARCHAR(255) NOT NULL, INDEX IDX_C1D030DC4654B4FD (talon_id), INDEX IDX_C1D030DC704716FE (pasajero_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hospedaje (id INT AUTO_INCREMENT NOT NULL, alojamiento_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, fecha_desde DATE NOT NULL, fecha_hasta DATE NOT NULL, habitaciones LONGTEXT NOT NULL, comentarios LONGTEXT DEFAULT NULL, INDEX IDX_D0926DF6FD574BC5 (alojamiento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE itinerario (id INT AUTO_INCREMENT NOT NULL, viaje_id INT NOT NULL, grupo_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, precio DOUBLE PRECISION DEFAULT NULL, fecha_inicio DATE DEFAULT NULL, fecha_fin DATE DEFAULT NULL, principal TINYINT(1) NOT NULL, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_11ECF40494E1E648 (viaje_id), INDEX IDX_11ECF4049C833003 (grupo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE itinerario_detalle (id INT AUTO_INCREMENT NOT NULL, itinerario_id INT NOT NULL, ciudad_id INT DEFAULT NULL, trayecto_id INT DEFAULT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, orden DOUBLE PRECISION DEFAULT NULL, INDEX IDX_DC0CE8B6B824E717 (itinerario_id), INDEX IDX_DC0CE8B6E8608214 (ciudad_id), INDEX IDX_DC0CE8B68E3E79AA (trayecto_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE link_pago_rifa (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, deposito_id INT DEFAULT NULL, comprador_nombre VARCHAR(255) NOT NULL, comprador_apellido VARCHAR(255) NOT NULL, comprador_email VARCHAR(255) NOT NULL, comprador_celular VARCHAR(255) NOT NULL, comprador_departamento VARCHAR(255) DEFAULT NULL, estado VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', encrypted_link VARCHAR(255) NOT NULL, geocom_token VARCHAR(255) DEFAULT NULL, asumir_recargo TINYINT(1) NOT NULL, INDEX IDX_6A4C3583704716FE (pasajero_id), UNIQUE INDEX UNIQ_6A4C35834140C3FC (deposito_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE link_pago_rifa_seleccion (id INT AUTO_INCREMENT NOT NULL, link_pago_rifa_id INT NOT NULL, tarjeta VARCHAR(255) DEFAULT NULL, tipo_tarjeta VARCHAR(255) DEFAULT NULL, cuotas SMALLINT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_2E97317A5869AF8E (link_pago_rifa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE link_pago_rifa_talones (id INT AUTO_INCREMENT NOT NULL, link_pago_rifa_id INT NOT NULL, talon_id INT NOT NULL, INDEX IDX_12149FA45869AF8E (link_pago_rifa_id), INDEX IDX_12149FA44654B4FD (talon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lista (id INT AUTO_INCREMENT NOT NULL, grupo_id INT NOT NULL, ciudad_id INT DEFAULT NULL, lista_estado_id INT DEFAULT NULL, itinerario_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) NOT NULL, limite_opciones INT DEFAULT NULL, disponible_hasta DATETIME DEFAULT NULL, fecha_programada DATETIME DEFAULT NULL, imagen VARCHAR(255) DEFAULT NULL, INDEX IDX_FB9FEEED9C833003 (grupo_id), INDEX IDX_FB9FEEEDE8608214 (ciudad_id), INDEX IDX_FB9FEEED72F7F1D0 (lista_estado_id), INDEX IDX_FB9FEEEDB824E717 (itinerario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lista_estado (id INT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lista_opcion (id INT AUTO_INCREMENT NOT NULL, lista_id INT NOT NULL, titulo VARCHAR(255) NOT NULL, descripcion VARCHAR(255) DEFAULT NULL, cupo_limite INT DEFAULT NULL, precio INT DEFAULT NULL, INDEX IDX_227314576736D68F (lista_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lote_rifa (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, cantidad_sorteos SMALLINT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', moneda VARCHAR(255) NOT NULL, anio VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notificacion (id INT AUTO_INCREMENT NOT NULL, grupo_id INT NOT NULL, itinerario_id INT DEFAULT NULL, ciudad_id INT DEFAULT NULL, lista_id INT DEFAULT NULL, titulo VARCHAR(200) NOT NULL, mensaje VARCHAR(255) NOT NULL, fecha_programada DATETIME DEFAULT NULL, foto VARCHAR(255) DEFAULT NULL, fecha_enviado DATETIME DEFAULT NULL, INDEX IDX_729A19EC9C833003 (grupo_id), INDEX IDX_729A19ECB824E717 (itinerario_id), INDEX IDX_729A19ECE8608214 (ciudad_id), INDEX IDX_729A19EC6736D68F (lista_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organizacion (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, rut VARCHAR(100) DEFAULT NULL, razon_social VARCHAR(150) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, telefono VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pago_personal (id INT AUTO_INCREMENT NOT NULL, deposito_id INT NOT NULL, fecha DATETIME NOT NULL, monto DOUBLE PRECISION NOT NULL, INDEX IDX_6637FA6D4140C3FC (deposito_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pais (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, nacionalidad VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero (id INT AUTO_INCREMENT NOT NULL, persona_id INT NOT NULL, itinerario_id INT NOT NULL, universidad_id INT NOT NULL, acompanante_id INT DEFAULT NULL, estado VARCHAR(255) NOT NULL, comentarios LONGTEXT DEFAULT NULL, pasaporte LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_17D4512BF5F88DB9 (persona_id), INDEX IDX_17D4512BB824E717 (itinerario_id), INDEX IDX_17D4512B271768CD (universidad_id), UNIQUE INDEX UNIQ_17D4512B4C735FDF (acompanante_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero_alojamiento (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, alojamiento_id INT NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, INDEX IDX_36E44E42704716FE (pasajero_id), INDEX IDX_36E44E42FD574BC5 (alojamiento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero_documento (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT DEFAULT NULL, documento_id INT DEFAULT NULL, fecha_creado DATETIME NOT NULL, INDEX IDX_997F86E704716FE (pasajero_id), INDEX IDX_997F86E45C0CF75 (documento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero_lista_opcion (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, lista_opcion_id INT NOT NULL, fecha_anotado DATETIME DEFAULT NULL, fecha_pago DATETIME DEFAULT NULL, INDEX IDX_F1B59563704716FE (pasajero_id), INDEX IDX_F1B59563E8100AF4 (lista_opcion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero_notificacion (id INT AUTO_INCREMENT NOT NULL, pasajero_id INT NOT NULL, notificacion_id INT NOT NULL, fecha_visto DATETIME DEFAULT NULL, INDEX IDX_A15C98D8704716FE (pasajero_id), INDEX IDX_A15C98D84D633FC4 (notificacion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pasajero_servicio (id INT AUTO_INCREMENT NOT NULL, servicio_id INT NOT NULL, pasajero_id INT NOT NULL, booking VARCHAR(255) DEFAULT NULL, estado VARCHAR(255) DEFAULT NULL, comentario LONGTEXT DEFAULT NULL, INDEX IDX_3D314D1971CAA3E7 (servicio_id), INDEX IDX_3D314D19704716FE (pasajero_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE persona (id INT AUTO_INCREMENT NOT NULL, nombres VARCHAR(255) NOT NULL, apellidos VARCHAR(255) NOT NULL, fecha_nacimiento DATE NOT NULL, direccion VARCHAR(255) DEFAULT NULL, cedula VARCHAR(255) NOT NULL, celular VARCHAR(255) DEFAULT NULL, sexo VARCHAR(100) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', id_externo INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE persona_token_firebase (id INT AUTO_INCREMENT NOT NULL, persona_id INT NOT NULL, token VARCHAR(255) NOT NULL, fecha_creado DATETIME DEFAULT NULL, fecha_actualizado DATETIME DEFAULT NULL, INDEX IDX_2378F936F5F88DB9 (persona_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE piques (id INT AUTO_INCREMENT NOT NULL, ciudad_id INT NOT NULL, titulo VARCHAR(255) DEFAULT NULL, descripcion LONGTEXT DEFAULT NULL, INDEX IDX_7EFD6B78E8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE proveedor (id INT AUTO_INCREMENT NOT NULL, pais_id INT DEFAULT NULL, ciudad_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, contacto VARCHAR(255) NOT NULL, forma_contacto VARCHAR(255) DEFAULT NULL, whatsapp VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, telefonos VARCHAR(255) DEFAULT NULL, mails VARCHAR(255) DEFAULT NULL, cuenta_bancaria LONGTEXT DEFAULT NULL, comentarios LONGTEXT DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, google_maps VARCHAR(255) DEFAULT NULL, maps_me VARCHAR(255) DEFAULT NULL, INDEX IDX_16C068CEC604D5C6 (pais_id), INDEX IDX_16C068CEE8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE punto_interes (id INT AUTO_INCREMENT NOT NULL, ciudad_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion LONGTEXT DEFAULT NULL, maps_me LONGTEXT DEFAULT NULL, google_maps LONGTEXT DEFAULT NULL, horarios VARCHAR(255) DEFAULT NULL, precio VARCHAR(255) DEFAULT NULL, tipo VARCHAR(255) DEFAULT NULL, orden DOUBLE PRECISION DEFAULT NULL, image_src VARCHAR(255) DEFAULT NULL, web_url VARCHAR(255) DEFAULT NULL, INDEX IDX_513CDE59E8608214 (ciudad_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_codes (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, expired_at DATETIME NOT NULL, is_used TINYINT(1) NOT NULL, INDEX IDX_6D52BC6FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rifa (id INT AUTO_INCREMENT NOT NULL, organizacion_id INT NOT NULL, nombre VARCHAR(150) NOT NULL, descripcion VARCHAR(255) DEFAULT NULL, fecha_inicio DATE DEFAULT NULL, fecha_fin DATE DEFAULT NULL, activa TINYINT(1) NOT NULL, INDEX IDX_AE66DA4B90B1019E (organizacion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE servicio (id INT AUTO_INCREMENT NOT NULL, transporte_id INT DEFAULT NULL, hospedaje_id INT DEFAULT NULL, grupo_id INT NOT NULL, cantidad INT DEFAULT NULL, nro_booking VARCHAR(255) DEFAULT NULL, precio_por_persona DOUBLE PRECISION DEFAULT NULL, comentarios LONGTEXT DEFAULT NULL, estado VARCHAR(255) DEFAULT NULL, INDEX IDX_CB86F22A24FC919A (transporte_id), INDEX IDX_CB86F22A195A2D00 (hospedaje_id), INDEX IDX_CB86F22A9C833003 (grupo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sorteo (id INT AUTO_INCREMENT NOT NULL, rifa_id INT NOT NULL, sorteo_numero INT NOT NULL, numero_inicial_talon INT NOT NULL, numero_final_talon INT NOT NULL, fecha_sorteo DATE NOT NULL, lugar VARCHAR(255) DEFAULT NULL, valor_talon DOUBLE PRECISION DEFAULT NULL, porcentaje_premio DOUBLE PRECISION DEFAULT NULL, INDEX IDX_705F75E0C5884E47 (rifa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subgrupo (id INT AUTO_INCREMENT NOT NULL, viaje_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_F6BD740994E1E648 (viaje_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE talon (id INT AUTO_INCREMENT NOT NULL, comprador_id INT DEFAULT NULL, pasajero_id INT DEFAULT NULL, deposito_id INT DEFAULT NULL, solicitante_id INT DEFAULT NULL, lote_rifa_id INT DEFAULT NULL, sorteo_id INT DEFAULT NULL, numero SMALLINT NOT NULL, fecha_sorteo DATE NOT NULL, estado VARCHAR(255) NOT NULL, precio SMALLINT NOT NULL, fecha_registro DATETIME DEFAULT NULL, fecha_entrega DATETIME DEFAULT NULL, sorteo_numero SMALLINT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', comentario VARCHAR(255) DEFAULT NULL, recaudacion DOUBLE PRECISION DEFAULT NULL, valor DOUBLE PRECISION DEFAULT NULL, INDEX IDX_40482807200A5E25 (comprador_id), INDEX IDX_40482807704716FE (pasajero_id), INDEX IDX_404828074140C3FC (deposito_id), INDEX IDX_40482807C680A87 (solicitante_id), INDEX IDX_40482807A8151442 (lote_rifa_id), INDEX IDX_40482807663FD436 (sorteo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tarjeta (id INT AUTO_INCREMENT NOT NULL, deposito_id INT NOT NULL, issuer VARCHAR(255) NOT NULL, moneda VARCHAR(255) NOT NULL, cuotas SMALLINT NOT NULL, fecha_transaccion DATETIME NOT NULL, codigo_autorizacion VARCHAR(255) NOT NULL, numero_tarjeta VARCHAR(255) DEFAULT NULL, acquirer VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', nombre_tarjeta VARCHAR(255) DEFAULT NULL, fecha_vencimiento VARCHAR(10) DEFAULT NULL, UNIQUE INDEX UNIQ_AE90B7864140C3FC (deposito_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tipo_documento (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transporte (id INT AUTO_INCREMENT NOT NULL, trayecto_id INT NOT NULL, transporte_tipo_id INT NOT NULL, proveedor_id INT DEFAULT NULL, trayecto_padre_id INT DEFAULT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, comentarios LONGTEXT DEFAULT NULL, orden DOUBLE PRECISION NOT NULL, duracion VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, hora_inicio VARCHAR(255) NOT NULL, hora_fin VARCHAR(255) NOT NULL, INDEX IDX_336ADCB48E3E79AA (trayecto_id), INDEX IDX_336ADCB4AC5ED017 (transporte_tipo_id), INDEX IDX_336ADCB4CB305D73 (proveedor_id), INDEX IDX_336ADCB4B29B48DA (trayecto_padre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transporte_tipo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trayecto (id INT AUTO_INCREMENT NOT NULL, ciudad_inicio_id INT NOT NULL, ciudad_fin_id INT NOT NULL, generico TINYINT(1) DEFAULT NULL, INDEX IDX_D1926D33B8954AAB (ciudad_inicio_id), INDEX IDX_D1926D339C9D3BA1 (ciudad_fin_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE universidad (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, persona_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649F5F88DB9 (persona_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_rol (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, rol VARCHAR(255) NOT NULL, INDEX IDX_E5435EBCA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE viaje (id INT AUTO_INCREMENT NOT NULL, viaje_madre_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion VARCHAR(255) DEFAULT NULL, anio SMALLINT NOT NULL, activo TINYINT(1) NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, titulo VARCHAR(255) DEFAULT NULL, subtitulo VARCHAR(255) DEFAULT NULL, destacado TINYINT(1) NOT NULL, token VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1D41ED163279E901 (viaje_madre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE viaje_madre (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, imagen VARCHAR(255) DEFAULT NULL, descripcion VARCHAR(255) DEFAULT NULL, tipo VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE aereopuerto ADD CONSTRAINT FK_17057EAE8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE alojamiento ADD CONSTRAINT FK_26918125DA231D27 FOREIGN KEY (alojamiento_tipo_id) REFERENCES alojamiento_tipo (id)');
        $this->addSql('ALTER TABLE alojamiento ADD CONSTRAINT FK_26918125CB305D73 FOREIGN KEY (proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE archivo ADD CONSTRAINT FK_3529B48245C0CF75 FOREIGN KEY (documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE campos_tipotransporte ADD CONSTRAINT FK_526485EEAC5ED017 FOREIGN KEY (transporte_tipo_id) REFERENCES transporte_tipo (id)');
        $this->addSql('ALTER TABLE ciudad ADD CONSTRAINT FK_8E86059EC604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE ciudad_campos ADD CONSTRAINT FK_80D6DA1E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE costo_extra ADD CONSTRAINT FK_68520204704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE datos_tipo_transporte ADD CONSTRAINT FK_FE07457CE847570D FOREIGN KEY (campos_tipo_transporte_id) REFERENCES campos_tipotransporte (id)');
        $this->addSql('ALTER TABLE datos_tipo_transporte ADD CONSTRAINT FK_FE07457C24FC919A FOREIGN KEY (transporte_id) REFERENCES transporte (id)');
        $this->addSql('ALTER TABLE datos_tipo_transporte ADD CONSTRAINT FK_FE07457C67CB2AE8 FOREIGN KEY (aereopuerto_id) REFERENCES aereopuerto (id)');
        $this->addSql('ALTER TABLE deposito ADD CONSTRAINT FK_509FC0D1704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC7F6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC7C604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC7F5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id)');
        $this->addSql('ALTER TABLE etiqueta_pasajero ADD CONSTRAINT FK_BE362F4BD53DA3AB FOREIGN KEY (etiqueta_id) REFERENCES etiqueta (id)');
        $this->addSql('ALTER TABLE etiqueta_pasajero ADD CONSTRAINT FK_BE362F4B704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE forgot_password ADD CONSTRAINT FK_2AB9B566A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE foto_persona ADD CONSTRAINT FK_43618E61F5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id)');
        $this->addSql('ALTER TABLE grupo ADD CONSTRAINT FK_8C0E9BD394E1E648 FOREIGN KEY (viaje_id) REFERENCES viaje (id)');
        $this->addSql('ALTER TABLE historial_transferencias ADD CONSTRAINT FK_C1D030DC4654B4FD FOREIGN KEY (talon_id) REFERENCES talon (id)');
        $this->addSql('ALTER TABLE historial_transferencias ADD CONSTRAINT FK_C1D030DC704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE hospedaje ADD CONSTRAINT FK_D0926DF6FD574BC5 FOREIGN KEY (alojamiento_id) REFERENCES alojamiento (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF40494E1E648 FOREIGN KEY (viaje_id) REFERENCES viaje (id)');
        $this->addSql('ALTER TABLE itinerario ADD CONSTRAINT FK_11ECF4049C833003 FOREIGN KEY (grupo_id) REFERENCES grupo (id)');
        $this->addSql('ALTER TABLE itinerario_detalle ADD CONSTRAINT FK_DC0CE8B6B824E717 FOREIGN KEY (itinerario_id) REFERENCES itinerario (id)');
        $this->addSql('ALTER TABLE itinerario_detalle ADD CONSTRAINT FK_DC0CE8B6E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE itinerario_detalle ADD CONSTRAINT FK_DC0CE8B68E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id)');
        $this->addSql('ALTER TABLE link_pago_rifa ADD CONSTRAINT FK_6A4C3583704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE link_pago_rifa ADD CONSTRAINT FK_6A4C35834140C3FC FOREIGN KEY (deposito_id) REFERENCES deposito (id)');
        $this->addSql('ALTER TABLE link_pago_rifa_seleccion ADD CONSTRAINT FK_2E97317A5869AF8E FOREIGN KEY (link_pago_rifa_id) REFERENCES link_pago_rifa (id)');
        $this->addSql('ALTER TABLE link_pago_rifa_talones ADD CONSTRAINT FK_12149FA45869AF8E FOREIGN KEY (link_pago_rifa_id) REFERENCES link_pago_rifa (id)');
        $this->addSql('ALTER TABLE link_pago_rifa_talones ADD CONSTRAINT FK_12149FA44654B4FD FOREIGN KEY (talon_id) REFERENCES talon (id)');
        $this->addSql('ALTER TABLE lista ADD CONSTRAINT FK_FB9FEEED9C833003 FOREIGN KEY (grupo_id) REFERENCES grupo (id)');
        $this->addSql('ALTER TABLE lista ADD CONSTRAINT FK_FB9FEEEDE8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE lista ADD CONSTRAINT FK_FB9FEEED72F7F1D0 FOREIGN KEY (lista_estado_id) REFERENCES lista_estado (id)');
        $this->addSql('ALTER TABLE lista ADD CONSTRAINT FK_FB9FEEEDB824E717 FOREIGN KEY (itinerario_id) REFERENCES itinerario (id)');
        $this->addSql('ALTER TABLE lista_opcion ADD CONSTRAINT FK_227314576736D68F FOREIGN KEY (lista_id) REFERENCES lista (id)');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19EC9C833003 FOREIGN KEY (grupo_id) REFERENCES grupo (id)');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19ECB824E717 FOREIGN KEY (itinerario_id) REFERENCES itinerario (id)');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19ECE8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19EC6736D68F FOREIGN KEY (lista_id) REFERENCES lista (id)');
        $this->addSql('ALTER TABLE pago_personal ADD CONSTRAINT FK_6637FA6D4140C3FC FOREIGN KEY (deposito_id) REFERENCES deposito (id)');
        $this->addSql('ALTER TABLE pasajero ADD CONSTRAINT FK_17D4512BF5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id)');
        $this->addSql('ALTER TABLE pasajero ADD CONSTRAINT FK_17D4512BB824E717 FOREIGN KEY (itinerario_id) REFERENCES itinerario (id)');
        $this->addSql('ALTER TABLE pasajero ADD CONSTRAINT FK_17D4512B271768CD FOREIGN KEY (universidad_id) REFERENCES universidad (id)');
        $this->addSql('ALTER TABLE pasajero ADD CONSTRAINT FK_17D4512B4C735FDF FOREIGN KEY (acompanante_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE pasajero_alojamiento ADD CONSTRAINT FK_36E44E42704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE pasajero_alojamiento ADD CONSTRAINT FK_36E44E42FD574BC5 FOREIGN KEY (alojamiento_id) REFERENCES alojamiento (id)');
        $this->addSql('ALTER TABLE pasajero_documento ADD CONSTRAINT FK_997F86E704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE pasajero_documento ADD CONSTRAINT FK_997F86E45C0CF75 FOREIGN KEY (documento_id) REFERENCES documento (id)');
        $this->addSql('ALTER TABLE pasajero_lista_opcion ADD CONSTRAINT FK_F1B59563704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE pasajero_lista_opcion ADD CONSTRAINT FK_F1B59563E8100AF4 FOREIGN KEY (lista_opcion_id) REFERENCES lista_opcion (id)');
        $this->addSql('ALTER TABLE pasajero_notificacion ADD CONSTRAINT FK_A15C98D8704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE pasajero_notificacion ADD CONSTRAINT FK_A15C98D84D633FC4 FOREIGN KEY (notificacion_id) REFERENCES notificacion (id)');
        $this->addSql('ALTER TABLE pasajero_servicio ADD CONSTRAINT FK_3D314D1971CAA3E7 FOREIGN KEY (servicio_id) REFERENCES servicio (id)');
        $this->addSql('ALTER TABLE pasajero_servicio ADD CONSTRAINT FK_3D314D19704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE persona_token_firebase ADD CONSTRAINT FK_2378F936F5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id)');
        $this->addSql('ALTER TABLE piques ADD CONSTRAINT FK_7EFD6B78E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE proveedor ADD CONSTRAINT FK_16C068CEC604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE proveedor ADD CONSTRAINT FK_16C068CEE8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE punto_interes ADD CONSTRAINT FK_513CDE59E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE reset_codes ADD CONSTRAINT FK_6D52BC6FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE rifa ADD CONSTRAINT FK_AE66DA4B90B1019E FOREIGN KEY (organizacion_id) REFERENCES organizacion (id)');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT FK_CB86F22A24FC919A FOREIGN KEY (transporte_id) REFERENCES transporte (id)');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT FK_CB86F22A195A2D00 FOREIGN KEY (hospedaje_id) REFERENCES hospedaje (id)');
        $this->addSql('ALTER TABLE servicio ADD CONSTRAINT FK_CB86F22A9C833003 FOREIGN KEY (grupo_id) REFERENCES grupo (id)');
        $this->addSql('ALTER TABLE sorteo ADD CONSTRAINT FK_705F75E0C5884E47 FOREIGN KEY (rifa_id) REFERENCES rifa (id)');
        $this->addSql('ALTER TABLE subgrupo ADD CONSTRAINT FK_F6BD740994E1E648 FOREIGN KEY (viaje_id) REFERENCES viaje (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_40482807200A5E25 FOREIGN KEY (comprador_id) REFERENCES comprador (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_40482807704716FE FOREIGN KEY (pasajero_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_404828074140C3FC FOREIGN KEY (deposito_id) REFERENCES deposito (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_40482807C680A87 FOREIGN KEY (solicitante_id) REFERENCES pasajero (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_40482807A8151442 FOREIGN KEY (lote_rifa_id) REFERENCES lote_rifa (id)');
        $this->addSql('ALTER TABLE talon ADD CONSTRAINT FK_40482807663FD436 FOREIGN KEY (sorteo_id) REFERENCES sorteo (id)');
        $this->addSql('ALTER TABLE tarjeta ADD CONSTRAINT FK_AE90B7864140C3FC FOREIGN KEY (deposito_id) REFERENCES deposito (id)');
        $this->addSql('ALTER TABLE transporte ADD CONSTRAINT FK_336ADCB48E3E79AA FOREIGN KEY (trayecto_id) REFERENCES trayecto (id)');
        $this->addSql('ALTER TABLE transporte ADD CONSTRAINT FK_336ADCB4AC5ED017 FOREIGN KEY (transporte_tipo_id) REFERENCES transporte_tipo (id)');
        $this->addSql('ALTER TABLE transporte ADD CONSTRAINT FK_336ADCB4CB305D73 FOREIGN KEY (proveedor_id) REFERENCES proveedor (id)');
        $this->addSql('ALTER TABLE transporte ADD CONSTRAINT FK_336ADCB4B29B48DA FOREIGN KEY (trayecto_padre_id) REFERENCES trayecto (id)');
        $this->addSql('ALTER TABLE trayecto ADD CONSTRAINT FK_D1926D33B8954AAB FOREIGN KEY (ciudad_inicio_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE trayecto ADD CONSTRAINT FK_D1926D339C9D3BA1 FOREIGN KEY (ciudad_fin_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F5F88DB9 FOREIGN KEY (persona_id) REFERENCES persona (id)');
        $this->addSql('ALTER TABLE user_rol ADD CONSTRAINT FK_E5435EBCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE viaje ADD CONSTRAINT FK_1D41ED163279E901 FOREIGN KEY (viaje_madre_id) REFERENCES viaje_madre (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE datos_tipo_transporte DROP FOREIGN KEY FK_FE07457C67CB2AE8');
        $this->addSql('ALTER TABLE hospedaje DROP FOREIGN KEY FK_D0926DF6FD574BC5');
        $this->addSql('ALTER TABLE pasajero_alojamiento DROP FOREIGN KEY FK_36E44E42FD574BC5');
        $this->addSql('ALTER TABLE alojamiento DROP FOREIGN KEY FK_26918125DA231D27');
        $this->addSql('ALTER TABLE datos_tipo_transporte DROP FOREIGN KEY FK_FE07457CE847570D');
        $this->addSql('ALTER TABLE aereopuerto DROP FOREIGN KEY FK_17057EAE8608214');
        $this->addSql('ALTER TABLE ciudad_campos DROP FOREIGN KEY FK_80D6DA1E8608214');
        $this->addSql('ALTER TABLE itinerario_detalle DROP FOREIGN KEY FK_DC0CE8B6E8608214');
        $this->addSql('ALTER TABLE lista DROP FOREIGN KEY FK_FB9FEEEDE8608214');
        $this->addSql('ALTER TABLE notificacion DROP FOREIGN KEY FK_729A19ECE8608214');
        $this->addSql('ALTER TABLE piques DROP FOREIGN KEY FK_7EFD6B78E8608214');
        $this->addSql('ALTER TABLE proveedor DROP FOREIGN KEY FK_16C068CEE8608214');
        $this->addSql('ALTER TABLE punto_interes DROP FOREIGN KEY FK_513CDE59E8608214');
        $this->addSql('ALTER TABLE trayecto DROP FOREIGN KEY FK_D1926D33B8954AAB');
        $this->addSql('ALTER TABLE trayecto DROP FOREIGN KEY FK_D1926D339C9D3BA1');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_40482807200A5E25');
        $this->addSql('ALTER TABLE link_pago_rifa DROP FOREIGN KEY FK_6A4C35834140C3FC');
        $this->addSql('ALTER TABLE pago_personal DROP FOREIGN KEY FK_6637FA6D4140C3FC');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_404828074140C3FC');
        $this->addSql('ALTER TABLE tarjeta DROP FOREIGN KEY FK_AE90B7864140C3FC');
        $this->addSql('ALTER TABLE archivo DROP FOREIGN KEY FK_3529B48245C0CF75');
        $this->addSql('ALTER TABLE pasajero_documento DROP FOREIGN KEY FK_997F86E45C0CF75');
        $this->addSql('ALTER TABLE etiqueta_pasajero DROP FOREIGN KEY FK_BE362F4BD53DA3AB');
        $this->addSql('ALTER TABLE itinerario DROP FOREIGN KEY FK_11ECF4049C833003');
        $this->addSql('ALTER TABLE lista DROP FOREIGN KEY FK_FB9FEEED9C833003');
        $this->addSql('ALTER TABLE notificacion DROP FOREIGN KEY FK_729A19EC9C833003');
        $this->addSql('ALTER TABLE servicio DROP FOREIGN KEY FK_CB86F22A9C833003');
        $this->addSql('ALTER TABLE servicio DROP FOREIGN KEY FK_CB86F22A195A2D00');
        $this->addSql('ALTER TABLE itinerario_detalle DROP FOREIGN KEY FK_DC0CE8B6B824E717');
        $this->addSql('ALTER TABLE lista DROP FOREIGN KEY FK_FB9FEEEDB824E717');
        $this->addSql('ALTER TABLE notificacion DROP FOREIGN KEY FK_729A19ECB824E717');
        $this->addSql('ALTER TABLE pasajero DROP FOREIGN KEY FK_17D4512BB824E717');
        $this->addSql('ALTER TABLE link_pago_rifa_seleccion DROP FOREIGN KEY FK_2E97317A5869AF8E');
        $this->addSql('ALTER TABLE link_pago_rifa_talones DROP FOREIGN KEY FK_12149FA45869AF8E');
        $this->addSql('ALTER TABLE lista_opcion DROP FOREIGN KEY FK_227314576736D68F');
        $this->addSql('ALTER TABLE notificacion DROP FOREIGN KEY FK_729A19EC6736D68F');
        $this->addSql('ALTER TABLE lista DROP FOREIGN KEY FK_FB9FEEED72F7F1D0');
        $this->addSql('ALTER TABLE pasajero_lista_opcion DROP FOREIGN KEY FK_F1B59563E8100AF4');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_40482807A8151442');
        $this->addSql('ALTER TABLE pasajero_notificacion DROP FOREIGN KEY FK_A15C98D84D633FC4');
        $this->addSql('ALTER TABLE rifa DROP FOREIGN KEY FK_AE66DA4B90B1019E');
        $this->addSql('ALTER TABLE ciudad DROP FOREIGN KEY FK_8E86059EC604D5C6');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC7C604D5C6');
        $this->addSql('ALTER TABLE proveedor DROP FOREIGN KEY FK_16C068CEC604D5C6');
        $this->addSql('ALTER TABLE costo_extra DROP FOREIGN KEY FK_68520204704716FE');
        $this->addSql('ALTER TABLE deposito DROP FOREIGN KEY FK_509FC0D1704716FE');
        $this->addSql('ALTER TABLE etiqueta_pasajero DROP FOREIGN KEY FK_BE362F4B704716FE');
        $this->addSql('ALTER TABLE historial_transferencias DROP FOREIGN KEY FK_C1D030DC704716FE');
        $this->addSql('ALTER TABLE link_pago_rifa DROP FOREIGN KEY FK_6A4C3583704716FE');
        $this->addSql('ALTER TABLE pasajero DROP FOREIGN KEY FK_17D4512B4C735FDF');
        $this->addSql('ALTER TABLE pasajero_alojamiento DROP FOREIGN KEY FK_36E44E42704716FE');
        $this->addSql('ALTER TABLE pasajero_documento DROP FOREIGN KEY FK_997F86E704716FE');
        $this->addSql('ALTER TABLE pasajero_lista_opcion DROP FOREIGN KEY FK_F1B59563704716FE');
        $this->addSql('ALTER TABLE pasajero_notificacion DROP FOREIGN KEY FK_A15C98D8704716FE');
        $this->addSql('ALTER TABLE pasajero_servicio DROP FOREIGN KEY FK_3D314D19704716FE');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_40482807704716FE');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_40482807C680A87');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC7F5F88DB9');
        $this->addSql('ALTER TABLE foto_persona DROP FOREIGN KEY FK_43618E61F5F88DB9');
        $this->addSql('ALTER TABLE pasajero DROP FOREIGN KEY FK_17D4512BF5F88DB9');
        $this->addSql('ALTER TABLE persona_token_firebase DROP FOREIGN KEY FK_2378F936F5F88DB9');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F5F88DB9');
        $this->addSql('ALTER TABLE alojamiento DROP FOREIGN KEY FK_26918125CB305D73');
        $this->addSql('ALTER TABLE transporte DROP FOREIGN KEY FK_336ADCB4CB305D73');
        $this->addSql('ALTER TABLE sorteo DROP FOREIGN KEY FK_705F75E0C5884E47');
        $this->addSql('ALTER TABLE pasajero_servicio DROP FOREIGN KEY FK_3D314D1971CAA3E7');
        $this->addSql('ALTER TABLE talon DROP FOREIGN KEY FK_40482807663FD436');
        $this->addSql('ALTER TABLE historial_transferencias DROP FOREIGN KEY FK_C1D030DC4654B4FD');
        $this->addSql('ALTER TABLE link_pago_rifa_talones DROP FOREIGN KEY FK_12149FA44654B4FD');
        $this->addSql('ALTER TABLE documento DROP FOREIGN KEY FK_B6B12EC7F6939175');
        $this->addSql('ALTER TABLE datos_tipo_transporte DROP FOREIGN KEY FK_FE07457C24FC919A');
        $this->addSql('ALTER TABLE servicio DROP FOREIGN KEY FK_CB86F22A24FC919A');
        $this->addSql('ALTER TABLE campos_tipotransporte DROP FOREIGN KEY FK_526485EEAC5ED017');
        $this->addSql('ALTER TABLE transporte DROP FOREIGN KEY FK_336ADCB4AC5ED017');
        $this->addSql('ALTER TABLE itinerario_detalle DROP FOREIGN KEY FK_DC0CE8B68E3E79AA');
        $this->addSql('ALTER TABLE transporte DROP FOREIGN KEY FK_336ADCB48E3E79AA');
        $this->addSql('ALTER TABLE transporte DROP FOREIGN KEY FK_336ADCB4B29B48DA');
        $this->addSql('ALTER TABLE pasajero DROP FOREIGN KEY FK_17D4512B271768CD');
        $this->addSql('ALTER TABLE forgot_password DROP FOREIGN KEY FK_2AB9B566A76ED395');
        $this->addSql('ALTER TABLE reset_codes DROP FOREIGN KEY FK_6D52BC6FA76ED395');
        $this->addSql('ALTER TABLE user_rol DROP FOREIGN KEY FK_E5435EBCA76ED395');
        $this->addSql('ALTER TABLE grupo DROP FOREIGN KEY FK_8C0E9BD394E1E648');
        $this->addSql('ALTER TABLE itinerario DROP FOREIGN KEY FK_11ECF40494E1E648');
        $this->addSql('ALTER TABLE subgrupo DROP FOREIGN KEY FK_F6BD740994E1E648');
        $this->addSql('ALTER TABLE viaje DROP FOREIGN KEY FK_1D41ED163279E901');
        $this->addSql('DROP TABLE aereopuerto');
        $this->addSql('DROP TABLE alojamiento');
        $this->addSql('DROP TABLE alojamiento_tipo');
        $this->addSql('DROP TABLE archivo');
        $this->addSql('DROP TABLE campos_tipotransporte');
        $this->addSql('DROP TABLE ciudad');
        $this->addSql('DROP TABLE ciudad_campos');
        $this->addSql('DROP TABLE comprador');
        $this->addSql('DROP TABLE costo_extra');
        $this->addSql('DROP TABLE datos_tipo_transporte');
        $this->addSql('DROP TABLE deposito');
        $this->addSql('DROP TABLE documento');
        $this->addSql('DROP TABLE etiqueta');
        $this->addSql('DROP TABLE etiqueta_pasajero');
        $this->addSql('DROP TABLE forgot_password');
        $this->addSql('DROP TABLE foto_persona');
        $this->addSql('DROP TABLE grupo');
        $this->addSql('DROP TABLE historial_transferencias');
        $this->addSql('DROP TABLE hospedaje');
        $this->addSql('DROP TABLE itinerario');
        $this->addSql('DROP TABLE itinerario_detalle');
        $this->addSql('DROP TABLE link_pago_rifa');
        $this->addSql('DROP TABLE link_pago_rifa_seleccion');
        $this->addSql('DROP TABLE link_pago_rifa_talones');
        $this->addSql('DROP TABLE lista');
        $this->addSql('DROP TABLE lista_estado');
        $this->addSql('DROP TABLE lista_opcion');
        $this->addSql('DROP TABLE lote_rifa');
        $this->addSql('DROP TABLE notificacion');
        $this->addSql('DROP TABLE organizacion');
        $this->addSql('DROP TABLE pago_personal');
        $this->addSql('DROP TABLE pais');
        $this->addSql('DROP TABLE pasajero');
        $this->addSql('DROP TABLE pasajero_alojamiento');
        $this->addSql('DROP TABLE pasajero_documento');
        $this->addSql('DROP TABLE pasajero_lista_opcion');
        $this->addSql('DROP TABLE pasajero_notificacion');
        $this->addSql('DROP TABLE pasajero_servicio');
        $this->addSql('DROP TABLE persona');
        $this->addSql('DROP TABLE persona_token_firebase');
        $this->addSql('DROP TABLE piques');
        $this->addSql('DROP TABLE proveedor');
        $this->addSql('DROP TABLE punto_interes');
        $this->addSql('DROP TABLE reset_codes');
        $this->addSql('DROP TABLE rifa');
        $this->addSql('DROP TABLE servicio');
        $this->addSql('DROP TABLE sorteo');
        $this->addSql('DROP TABLE subgrupo');
        $this->addSql('DROP TABLE talon');
        $this->addSql('DROP TABLE tarjeta');
        $this->addSql('DROP TABLE tipo_documento');
        $this->addSql('DROP TABLE transporte');
        $this->addSql('DROP TABLE transporte_tipo');
        $this->addSql('DROP TABLE trayecto');
        $this->addSql('DROP TABLE universidad');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_rol');
        $this->addSql('DROP TABLE viaje');
        $this->addSql('DROP TABLE viaje_madre');
    }
}
