name: Depoly Prod

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftpupload.net
        username: if0_41246838
        password: JnSt0MGYoN7oLmx
        protocol: ftp
        server-dir: toqueytoque-rifas.ct.ws/htdocs/api/
        timeout: 60000